services:
  client:
    build:
      context: ./client
    ports:
      - "80:80"
  server:
    restart: always
    build:
      context: ./
    ports:
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
