version: '3.9'
services:
  client:
    build:
      context: ./client
    ports:
      - "80:80"
  server:
    restart: always
    environment:
      - ROS_SERVER_IP=${ROS_SERVER_IP}
    build:
      context: ./
    ports:
      - "3001:3001"
